### ISSUE TITLE
can't get probabilities for classification

### ISSUE THREAD

**Issue by lorenzoromagnoli** [fiebrink1/wekinator#12]
I'm building a little project based on wekinaror and doing some sound analysis in processing and sending the data to wekinator to classify the type of sounds recorded. 

I'm looking for a way to understand when the system has no sufficient training data to determine the class. I thought I could read the value of the probability and set a threshold inside the receiving program. However I'm unable to get the probability data out. 

I tried doing this, but got nothing. 
> For classification outputs, you have the option of sending another OSC message containing the posterior probabilities for each class. This is turned off by default. To turn it on, click the model’s Edit button, then edit the name and type, and check the box to “Send class probabilities via OSC.” The OSC message name will be the same as the output name, with a “/” prepended (you will see a confirmation of this message name when you check this box).

**Comment by smarques** [comment]
👍  same problem here

**Comment by fiebrink1** [comment]
What version of Wekinator are you using? I've double checked this in the most recent version and I believe it is working. You can test with this Processing example, which will run with a 5-class classifier with probabilities turned on: http://www.doc.gold.ac.uk/~mas01rf/WekinatorDownloads/wekinator_examples/all_source_zips/Processing_SimpleDistribution_1Classifier.zip
