### ISSUE TITLE
OSC train->run

### ISSUE THREAD

**Issue by mzed** [fiebrink1/wekinator#14]
When controlling Wekinator with OSC, it's hard to know when to call run after calling train. Could Wekinator return a message when training is complete? Or, could there be a /wekinator/control/trainAndRun message, that asks Wekinator to switch to run mode when training is complete?

**Comment by Louismac** [comment]
I put in a OSC message that outputs  /wekinator/status/training-done last week for Balandino, its in the latest commit to master

**Comment by Louismac** [comment]
sorry, "/wekinator/status/done-training"

**Comment by mzed** [comment]
Does that come back on port 12000 with the rest of the output? That sounds perfect to me.

**Comment by Louismac** [comment]
Yes, whatever you have the output port set to for the model output

**Comment by mzed** [comment]
Thanks!
