### ISSUE TITLE
OSC doesn't understand doubles

### ISSUE THREAD

**Issue by mzed** [fiebrink1/wekinator#17]
I just ran into an issue where I tried to send a message with doubles, which didn't work.  Specifically, `/wekinator/control/outputs 1.0` doesn't update the value if the number is a double.

This came from Max, the o.pack object. There is an o.downcast object that causes messages to conform to OSC 1.0.  But, it seems like the OSC package in Wekinator isn't handling the newer OSC spec.

**Comment by fiebrink1** [comment]
Thanks for pointing this out. I'm not sure it's worth it to add support for OSC doubles, since all the Wekinator documentation does specify that it's float-only and this doesn't seem to be an issue for others.
