### ISSUE TITLE
Feature request: additional OSC control methods (or alternatively an easy way to log user actions)

### ISSUE THREAD

**Issue by DocSunset** [fiebrink1/wekinator#22]
Hi all.

I'm currently looking into conducting a study similar to [this one](https://www.nime.org/proceedings/2020/nime2020_paper55.pdf) only using Wekinator instead of libmapper+Webmapper as the mapping design platform. One important aspect of this research is recording the actions participants take when designing their mappings. With libmapper this was trivial, since every action is announced on a multicast UDP bus that's easy to eavesdrop on.

In order to record user interaction with Wekinator, the simplest solution that jumped to mind would be to re-create the GUI in Max, have users interact with this thin Max wrapper which I can write logging logic for, and then control the actual Wekinator by sending OSC control messages as documented [here](http://www.wekinator.org/detailed-instructions/#Controlling_Wekinator_via_OSC_messages) and implemented [here](https://github.com/fiebrink1/wekinator/blob/040f1d1e8c59c03959dc92f36b17f5e2576fecdb/src/wekimini/osc/OSCControlReceiver.java). This avoids having to add any interaction logging functionality to Wekinator, and allows me to record things like if a user deletes all the training data and starts over or changes the input-output associations. But it unfortunately would mean that my participants don't have access to a few very useful features of the GUI. 

Notably the delete last recording and re-add last recording buttons don't have OSC control methods associated with them. All of the other main features in the GUI that I would expect participants in my study to use are easy controlled via OSC. 

How difficult would it be to implement OSC methods for these last two buttons? I am not particularly familiar with Java, but I would be happy to try to hack it together myself if someone could help point me in the right direction.

Alternatively, if Wekinator already has a user interaction logging facility hidden somewhere deep inside, that would work for my purposes as well.

Thanks for you time and assistance.

Travis West

**Comment by Louismac** [comment]
Hi Travis 

There is a version of Wekinator called Wekinator-Kadenze (www.wekinator.org/kadenze/) Which is used for the online course. It has logging built in and functions largely the same as Wekinator normal, apart from when you open it you get a choice of assignments in a drop down. If you get your participants to select any of the assignments (e.g. Assignment 1, Part 1) then their actions will be logged in to a text file in the specified save directory. 

Check if this logs the things you want, if not we can talk about adding some more stuff in, I've done that for my own reserach before 

Best

Louis

**Comment by Louismac** [comment]
Oh, the buffer is only flushed (and logs updated) when you exit the project

**Comment by DocSunset** [comment]
Hi Louis,

Wekinator-Kadenze seems to have exactly the kind of logging I need! This is perfect. Thanks so much for bringing it to my attention.
