### ISSUE TITLE
Using Wekinator as a library or non-graphical application

### ISSUE THREAD

**Issue by lpil** [fiebrink1/wekinator#3]
Hello!

I'm a little stuck in my Unix-y ways, and as a result am interested in using Wekinator as a JVM library (or even as a headless daemon) rather than a graphical application. Is this easy/feasible/sensible?

Thanks,
Louis

**Comment by brannondorsey** [comment]
Hi, I am also interested in doing this. Or at least launching Wekinator from the windows command line opening .wekproj without the GUI.

**Comment by rustynymph** [comment]
Following

**Comment by brannondorsey** [comment]
I've got a fork that allows you to run wekinator projects from the command line [here](https://github.com/brannondorsey/wekimini).
