### ISSUE TITLE
OSC startDtwRecording message automatically sends a stopRunning command

### ISSUE THREAD

**Issue by Nagasaki45** [fiebrink1/wekinator#7]
I read the source code and this behavior seems to be intended, but I can't see why.
In dynamic time warp mode, when I'm using the GUI I can record gestures while the wekinator is still running. Is there a reason for the difference in behavior when using OSC to control the wekinator (`/wekinator/control/startDtwRecording`)?

**Comment by reubenxdsilva** [comment]
@Nagasaki45  try this
OSCMessage msg (“/wekinator/control/stopDtwRecording”);
msg.add(GestureNumber);
Rename your gesture name output in Wekinator to match the gesture number

**Comment by Nagasaki45** [comment]
Hi @reubenxdsilva, thanks for responding. This was so much time ago, I barely remember the context. If you think that there's no issue here or that it was already fixed feel free to close the ticket.
